(function(g){var window=this;var f3=function(a){var b={languageCode:a.i,languageName:a.l,displayName:g.$z(a),kind:a.o,name:a.A,id:a.I,is_servable:a.C,is_default:a.isDefault,is_translateable:a.F,vss_id:a.B};a.g&&(b.translationLanguage=a.g);return b},g3=function(a){return a.g?a.g.languageCode:a.i},Ipa=function(a,b){var c=new g.Zz;
c.i=a.i;c.l=a.l;c.A=a.A;c.o=a.o;c.isDefault=!1;c.C=a.C;c.F=a.F;c.B=a.B;c.G=a.G;c.g=b;return c},h3=function(a){if(!Jpa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Kpa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Lpa=function(){this.i=[];
this.g=[]},i3=function(a,b){return b?a.g.concat(a.i):a.g},j3=function(a,b){switch(b.o){case "asr":var c=a.i;
g.Xa(c,(0,g.x)(b.vr,b))||c.push(b);break;default:c=a.g,g.Xa(c,(0,g.x)(b.vr,b))||c.push(b)}},k3=function(){g.A.call(this);
this.i=new Lpa;this.A=[]},l3=function(a,b,c){k3.call(this,a);
this.g=null;this.A=b.Su;this.l=c},m3=function(){this.Xa=[]},n3=function(a,b,c,d,e,f){g.A.call(this);
this.I=a;this.o=b;this.A=new m3;this.g=null;this.C=d;this.J=f;this.i=this.l=null;this.T=c;this.B=e||!1;this.F=new g.J(this.vx,1E3,this);g.B(this,this.F);this.G=new g.Xs(this);g.B(this,this.G);this.G.L(b,"SEEK_COMPLETE",this.Vx);this.Vx();this.vx()},o3=function(a,b){var c=g.Xv(g.gw(b,a.I,{})),d={format:"RAW",
withCredentials:!0};a.B&&(d.responseType="arraybuffer");a.i=g.Fr(c,d,3,100).then((0,g.x)(a.dL,a));a.l=b;c=a.A;d=a.l.g[0].i;var e=g.ob(c.Xa,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Xa[e-1]&&e<c.Xa.length&&1==c.Xa[e]-d?(g.bb(c.Xa,e),g.bb(c.Xa,e-1)):0<e&&1==d-c.Xa[e-1]?c.Xa[e-1]=d:e<c.Xa.length&&1==c.Xa[e]-d?c.Xa[e]=d:(g.kb(c.Xa,e,0,d),g.kb(c.Xa,e+1,0,d)))},p3=function(a,b){k3.call(this,g.X(b));
this.g=a;this.C=b;this.l=null;this.o=!1;this.B=g.Hz(g.X(this.C))&&!this.g.i},q3=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.JV(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.Zz({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Mpa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},r3=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.JV(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},s3=function(a,b,c,d,e){k3.call(this,e||null);
c=c||g.Mq(a).hl||"";c=c.split("_").join("-");this.o=g.Oq(a,{hl:c});this.l=b;this.B=!!d;this.C={};this.g=null},t3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.xE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.l=f;this.g=k},u3=function(a,b,c,d,e){g.xE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.g=[]},w3=function(a){a=void 0===a?{}:a;
var b="_"+v3++;return new u3(0,0x8000000000000,0,b,a)},y3=function(a,b,c,d,e,f){var k={};
g.Ra(k,b);g.Ra(k,a.params);g.Ra(k,c);var l={};g.Ra(l,b.xb);a.params.xb&&g.Ra(l,a.params.xb);g.Ra(l,c.xb);k.xb=l;g.V.call(this,{D:"div",H:"caption-window",M:{id:"caption-window-"+a.id,dir:1==k.He?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},K:[{D:"span",H:"captions-text",M:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.R=!1;this.o=a;this.Z=this.U=null;this.Sa=e;this.Ra=f;this.F=null;this.aa=.96*e;this.ya=.96*f;this.l=k;this.Ka=c;this.B=this.i["captions-text"];this.Ca=
null!=this.B.style["box-decoration-break"]||null!=this.B.style["-webkit-box-decoration-break"];this.Y=d/360*16;this.type=0;this.ma=this.Y*x3(l);a=new g.ct(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.tG,this);a.subscribe("dragmove",this.sG,this);a.subscribe("dragend",this.rG,this);this.xa=this.oa=0;b="";this.l.windowOpacity&&(a=h3(this.l.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");a={"background-color":b,display:!1===this.l.isVisible?"none":"","text-align":Npa[this.l.textAlign]};
this.Ca&&(a["border-radius"]=b?this.ma/8+"px":"");if(this.A=2==this.o.params.He||3==this.o.params.He)b=this.element,c="vertical-rl",1==this.l.VA&&(c="vertical-lr"),g.Ld&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.yh(b,"-o-writing-mode",c),g.yh(b,"-webkit-writing-mode",c),g.yh(b,"writing-mode",c),g.yh(b,"text-orientation","upright"),g.H(b,"ytp-vertical-caption"),3==this.o.params.He&&(g.yh(b,"text-orientation",""),g.yh(b,"transform","rotate(180deg)"));g.yh(this.element,a);switch(this.l.Yf){case 0:case 1:case 2:g.H(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.H(this.element,"ytp-caption-window-bottom")}},x3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},z3=function(a,b){var c={},d=b.background?b.background:a.l.xb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.xb.backgroundOpacity;d=h3(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ca&&(c["box-decoration-break"]="clone",c["border-radius"]=a.ma/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Y*x3(b)+"px";d=1;e=b.color||a.l.xb.color;if(b.color||null!=b.textOpacity)e=h3(e),d=null==b.textOpacity?a.l.xb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.av&&(k=e=b.av);var l=a.Y/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),r=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=r;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.nr()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.xb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.We&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.rE&&(c.visibility="hidden");1==b.tE&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.Jz||g.Kz,3==a.o.params.He?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.Ge||2==b.Ge||3==b.Ge||4==b.Ge||5==b.Ge)if(g.Jz)c["font-weight"]="bold";else switch(c["text-emphasis"]="filled circle",c["webkit-text-emphasis"]="filled circle",b.Ge){case 4:case 3:c["text-emphasis-position"]="under right";c["webkit-text-emphasis-position"]="under right";break;
case 5:case 2:c["text-emphasis-position"]="over left",c["webkit-text-emphasis-position"]="over left"}return c},A3=function(a){a.F=g.Rd("SPAN");
g.yh(a.F,{display:"block"});g.H(a.F,"caption-visual-line");a.B.appendChild(a.F)},B3=function(a,b){var c=g.Rd("SPAN");
g.yh(c,{display:"inline-block","white-space":"pre-wrap"});g.yh(c,z3(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.yh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.yh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},C3=function(a,b,c){a.R=a.R||!!c;
var d={};g.Ra(d,a.l.xb);g.Ra(d,c||b.g);g.Ra(d,a.Ka.xb);(c=!a.F)&&A3(a);for(var e=a.U&&a.Z&&g.ac(d,a.Z)?a.U:B3(a,d),f=g.Da(b.text),k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.l,n=k[l];m&&!c?(A3(a),e=B3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Sd(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.Jz||!g.Ch(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Ch(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),g.Nd?g.yh(e,m,"1em"):
g.yh(e,m,"0.5em")))}a.Z=d;a.U=e;a.C.push(b)},D3=function(){},F3=function(){this.o=this.i=this.mode=this.l=0;
this.A=new E3(this);this.B=new E3(this);this.g=[];this.clear()},Opa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ll:a,
Ml:b,result:0};a=G3[a];b=G3[b];if(a&128){if(!(b&128)&&0!=c.g&&c.i==b)return{Ll:a,Ml:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ll:a,Ml:b,result:2};return{Ll:a,Ml:b,result:3}},Ppa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.o&&a.reset(),a.A.g.clear(),a.B.g.clear()):(a.o=0,H3(a.A,b,c,d))},Qpa=function(a,b){a.g.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.i=d.time;0==d.type?Ppa(a,d.Uu,d.Vu,b):1==d.type&&a.l&496&&H3(a.B,d.Uu,d.Vu,b)}a.g.length=0},I3=function(){this.g=0},J3=function(){this.i=this.l=this.g=0},K3=function(){this.timestamp=this.Yd=0},L3=function(a){this.l=[];
for(var b=0;15>=b;b++){this.l[b]=[];for(var c=0;32>=c;c++)this.l[b][c]=new K3}this.g=this.i=this.row=0;this.style=new I3;this.A=a;this.o=0},M3=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.A.i+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var r=a.l[m][p];
if(0!=r.Yd){0==c&&(c=m,d=p);n=String.fromCharCode(r.Yd);var w=r.timestamp;w<e&&(e=w);r.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==r.Yd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.A(c,d,e,l,f)}else for(d=c=0,f=e=a.A.i+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.l[k][m],r=p.Yd,0!=r&&(0==c&&(c=k,d=m),n=String.fromCharCode(r),w=p.timestamp,w<=e&&(e=w),l+=n,p.reset()),32==m||0==r)l&&b.A(c,d,e,f,l),e=f,l="",d=c=0},Vpa=function(a,b){switch(a){case 0:return Rpa[(b&127)-32];
case 1:return Spa[b&15];case 2:return Tpa[b&31];case 3:return Upa[b&31]}return 0},N3=function(a){return a.l[a.row][a.i]},O3=function(a,b,c){2<=b&&1<a.i&&(--a.i,N3(a).Yd=0);
var d=N3(a);d.timestamp=a.A.i+0;d.Yd=Vpa(b,c);32>a.i&&a.i++},P3=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.l[b+e][f].jg(a.l[c+e][f])},Q3=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.l[b+d][e].reset()},R3=function(a){a.row=0<a.g?a.g:1;
a.i=1;Q3(a,0,15)},S3=function(a){this.o=a;
this.A=0;this.style=new I3;this.B=new L3(a);this.C=new L3(a);this.F=new L3(a);this.i=this.B;this.l=this.C;this.g=this.i},T3=function(a,b,c){var d=a.i,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:M3(d,c),R3(a.i),R3(a.l),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.o.mode=1<<d.o;e?d.i=1:d.g!=b&&(d.g>b?(M3(d,c),Q3(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},U3=function(a){a.style.set(1);
a.g=a.l;a.g.g=0;a.g.style=a.style;a.o.mode=1<<a.g.o},V3=function(a){a.style.set(4);
a.g=a.F;a.g.style=a.style;a.o.mode=1<<a.g.o},E3=function(a){this.i=a;
this.g=new J3;this.A=0;this.l=new S3(a);this.B=new S3(a);this.o=this.l},H3=function(a,b,c,d){a.g.update();
b=Opa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ll;c=b.Ml;if(32<=e||!e)a.i.mode&a.i.l&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.o.g,b&96&&O3(a,0,b),c&96&&O3(a,0,c),0!=b&&0!=c&&3==a.style.g&&M3(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.l=e,b.i=c,b.g=2,b=e&8?a.B:a.l,a.o=b,a.i.mode=1<<(a.A<<2)+(b.A<<1)+(4==b.style.g?1:0),(a.i.mode|1<<(a.A<<2)+(b.A<<1)+(4!=b.style.g?1:0))&a.i.l))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;P3(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));Q3(c,b,e)}}c.row=d;c.i=a+1}else switch(e&7){case 1:switch(c&112){case 32:O3(b.g,0,32);break a;case 48:57==c?(d=b.g,N3(d).Yd=0,32>d.i&&d.i++):O3(b.g,1,c&15)}break;case 2:c&32&&O3(b.g,2,c&31);break;case 3:c&32&&O3(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:U3(b);break;case 33:d=
b.g;1<d.i&&(--d.i,N3(d).Yd=0);break;case 36:d=b.g;b=N3(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.l[a][c]==b){for(;32>=c;c++)d.l[a][c].reset();break}break;case 37:T3(b,2,d);break;case 38:T3(b,3,d);break;case 39:T3(b,4,d);break;case 40:O3(b.g,0,32);break;case 41:b.style.set(2);b.g=b.i;b.g.g=0;b.g.style=b.style;b.o.mode=1<<b.g.o;break;case 42:d=b.F;d.g=15;d.style.set(4);R3(d);V3(b);break;case 43:V3(b);break;case 44:a=b.i;switch(b.style.get()){case 1:case 2:case 3:M3(a,d)}Q3(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.i=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;M3(a,d);P3(a,b,b+1,a.g-1);Q3(a,a.row,1)}break;case 46:Q3(b.l,0,15);break;case 47:M3(b.i,d),b.l.updateTime(b.o.i+0),d=b.l,b.l=b.i,b.i=d,U3(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.g,32<(d.i+=c&3)&&(d.i=32)}}},W3=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.hd){var n=f[1],p=f[2],r=f[3];l.getAttribute("p");l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");r.getAttribute("t");f=g.Rd("RUBY");l=l.textContent;var w=g.Rd("SPAN");w.innerText=l;f.appendChild(w);n.getAttribute("p");w=g.Rd("RP");l=n.textContent;w.innerText=l;f.appendChild(w);k=k[p.getAttribute("p")];l=p.textContent;p=g.Rd("RT");p.innerText=l;f.appendChild(p);l=k.hd;if(10==l||11==l||12==l||13==l||14==l)if(g.yh(p,"text-emphasis","filled circle"),g.yh(p,"webkit-text-emphasis","filled circle"),
k.hd==k.hd==11||13==k.hd)g.yh(p,"webkit-text-emphasis-position","under left"),g.yh(p,"text-emphasis-position","under left");if(4==k.hd||7==k.hd||12==k.hd||14==k.hd)g.yh(f,"ruby-position","over"),g.yh(f,"-webkit-ruby-position","before");else if(5==k.hd||6==k.hd||11==k.hd||13==k.hd)g.yh(f,"ruby-position","under"),g.yh(f,"-webkit-ruby-position","after");r.getAttribute("p");l=r.textContent;r=g.Rd("RP");r.innerText=l;f.appendChild(r);return new t3(a,b,e,c,f,d,m)}switch(m.hd){case 9:case 10:m.Ge=1;break;
case 11:m.Ge=2;break;case 12:m.Ge=3;break;case 13:m.Ge=4;break;case 14:m.Ge=5}return new t3(a,b,e,c,l.textContent||"",d,m)},X3=function(){g.A.apply(this,arguments)},Y3=function(a){X3.call(this);
this.l={};this.G={};this.I={};this.A="_"+v3++;this.B=a;this.F={};this.i=this.g=null;this.C=!0},Z3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},$3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},a4=function(a,b){var c=Z3(a,b);
return void 0!=c?c:null},c4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return b4.test(c),c},d4=function(a,b){var c={},d=b.getAttribute("ws");
g.Ra(c,d?a.I[d]:a.B);d=a4(b,"mh");null!=d&&(c.mr=d);d=a4(b,"ju");null!=d&&(c.textAlign=d);d=a4(b,"pd");null!=d&&(c.He=d);d=a4(b,"sd");null!=d&&(c.VA=d);d=c4(b,"wfc");null!=d&&(c.windowColor=d);d=Z3(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},e4=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Ra(c,a.G[d]);d=a4(b,"ap");null!=d&&(c.Yf=d);d=Z3(b,"cc");null!=d&&(c.Zl=d);d=Z3(b,"ah");null!=d&&(c.Xe=d);d=Z3(b,"rc");null!=d&&(c.Mk=d);d=Z3(b,"av");null!=d&&(c.Jg=d);return c},f4=function(a,b,c,d){var e={};
g.Ra(e,e4(a,b));g.Ra(e,d4(a,b));d?g.ac(e,a.B)?(d=a.A,e=a.B):d="_"+v3++:d=b.getAttribute("id")||"_"+v3++;a=Z3(b,"t")+c;b=Z3(b,"d")||0x8000000000000;if(2==e.He||3==e.He)c=e.Mk,e.Mk=e.Zl,e.Zl=c;return new u3(a,b,0,d,e)},g4=function(a,b,c,d,e,f,k){y3.call(this,a,b,c,d,e,f,k);
this.type=1},h4=function(a,b,c){this.C=c;
this.version=this.B=this.o=this.g=0;this.i=new DataView(a);this.l=[]},i4=function(a){var b=a.g;
a.g+=1;return a.i.getUint8(b)},j4=function(a){var b=a.g;
a.g+=4;return a.i.getUint32(b)},k4=function(a,b){X3.call(this);
this.i=a;this.track="CC3"==b.l?4:0;this.g=new F3;this.g.l=1<<this.track},m4=function(a){if(g.Da(a))return!1;
a=new h4(a,8,0);return l4(a)},l4=function(a){if(!(a.g<a.i.byteLength)||1380139777!=j4(a))return!1;
a.version=i4(a);if(1<a.version)return!1;i4(a);i4(a);i4(a);return!0},n4=function(a,b,c,d,e,f,k){y3.call(this,a,b,c,d,e,f,k);
g.H(this.element,"ytp-caption-window-rollup");this.type=2;this.G=[];this.J=this.I=this.ha=0;this.N=NaN;this.za=0;this.Fa=null;this.fa=new g.J(this.iL,433,this);g.B(this,this.fa)},Wpa=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Xpa=function(a){if(isNaN(a.N)){var b=a.l.Zl;
if(b){var c=g.Rd("SPAN");g.ae(c,"\u2013".repeat(b));g.yh(c,z3(a,a.l.xb));a.B.appendChild(c);a.N=c.offsetWidth;a.B.removeChild(c)}else a.N=0}return a.N},Ypa=function(a,b){if(!b)return"";
a.A&&1!=a.o.params.VA&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},o4=function(a){a.G=[].concat(g.ea(document.getElementsByClassName("caption-visual-line")));
for(var b=a.o.params.Mk,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.I=d;a.J=Math.max(Xpa(a),a.za,Wpa(a,a.B))},Zpa=function(a,b){o4(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.I-c;if(c!=a.ha){var d=0<c&&0==a.ha;b||isNaN(c)||d||(g.H(a.element,"ytp-rollup-mode"),g.Eo(a.fa));g.yh(a.B,"transform",Ypa(a,c));a.ha=c}o4(a)},p4=function(){X3.call(this)},q4=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.We=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new t3(b,c,d,e.id,p.nodeValue,f||0<n,g.Xb(l)?void 0:l);m.push(p);var r=e;g.B(r,p);r.g.push(p)}else r={},g.Ra(r,l),q4(a,b,c,d,e,!0,p,r,m)}},r4=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+parseFloat(c.value);return 1E3*b},s4=function(a,b,c,d){d=Object.assign({mr:0},d);
return new u3(a,b,c,"_"+v3++,d)},t4=function(a){g.A.call(this);
this.i=a;this.g=null},w4=function(a){g.uL.call(this,a);
this.l=g.X(a);this.P=a.getVideoData();this.oa=g.RK(a);this.N=a;var b=null,c=g.rp("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.bp(c));this.ba=b;this.o={xb:{}};this.A={xb:{}};this.G=[];this.T={};this.U={};this.J=!1;this.fa=g.KV(this.P,this.N);this.xa=!!this.P.captionTracks.length;this.ya=!!this.P.oj;this.ra="3"==this.l.l;b=a.app.A;c=!(!b||!b.bl());this.ma=!(!b||!b.Hh());this.B=this.ra&&c&&!this.fa;this.I=!this.B&&this.ra&&this.ma&&this.fa;this.i=this.C=this.F=this.R=this.ha=null;this.Z=
new t4(this.l);g.B(this,this.Z);c=b=this.g=null;this.B||(b=new g.xo(this.lB,void 0,this),g.B(this,b),c=new g.J(this.MM,2E3,this),g.B(this,c));this.Y=b;this.aa=c;this.da=new g.Xs(this);g.B(this,this.da);this.B||this.da.L(a,"resize",this.wt);this.da.L(a,"onPlaybackAudioChange",this.JI);this.da.L(a,g.AE("captions"),this.zF,this);this.da.L(a,"crx_captions",this.AF,this);u4(this,v4(this,"display-settings")||{})},x4=function(a){if(1==a.l.eg||1==a.P.eg||"alwayson"==g.gC(a.P,"yt:cc"))return!0;
if(2==a.l.eg){var b=v4(a,"module-enabled");if(null!=b)return!!b}if(a.P.captionTracks.length)var c=a.player.getAudioTrack().zp;return"ON"==c||"on"==g.gC(a.P,"yt:cc")},y4=function(a,b){if(a.g&&(void 0===b||!b)||!a.P.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.om||"FORCED_ON"==c.zp},A4=function(a,b){if(a.i){if(a.C&&a.C.g)return a.C.g;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=i3(a.i.i,c);for(var d=[a.P.dg,a.l.dg,g.gC(a.P,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(g3(c[f])==d[e])return c[f];return a.C&&a.C.Qp?a.C.Qp:(d=c.find(function(k){return k.isDefault}))?d:c[0]||z4(a)}return null},z4=function(a){return a.C&&a.C.om},B4=function(a){var b=z4(a);
return!!b&&a.g==b},C4=function(a,b){for(var c=a.N.app.A.ia().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},E4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.J=c,a.J&&D4(a,"module-enabled",!!b));a.g=b;y4(a)&&(a.g=z4(a));a.load()},$pa=function(a,b){var c=a.oa.getVideoContentRect(!0).height;
if(!c)return null;var d=a.oa.getPlayerSize();switch(null!=b.params.mr?b.params.mr:1<b.g.length?1:0){case 1:return new g4(b,a.o,a.A,c,d.width,d.height,a.l.experiments);case 2:return new n4(b,a.o,a.A,c,d.width,d.height,a.l.experiments);default:return new y3(b,a.o,a.A,c,d.width,d.height,a.l.experiments)}},u4=function(a,b,c){var d=F4.xb;
a.o={};g.Ra(a.o,F4);a.o.xb={};g.Ra(a.o.xb,d);a.A={xb:{}};var e=b.backgroundOverride?a.A:a.o,f=b.background||d.background;b4.test(f);e.xb.background=f;e=b.colorOverride?a.A:a.o;f=b.color||d.color;b4.test(f);e.xb.color=f;e=b.windowColorOverride?a.A:a.o;f=b.windowColor||F4.windowColor;b4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.A:a.o;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.xb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.A:a.o;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.xb.fontSizeIncrement=f;f=b.fontStyleOverride?a.A:a.o;e=b.fontStyle;null==e&&(e=d.bold&&d.We?3:d.bold?1:d.We?2:0);f=f.xb;switch(e){case 1:f.bold=!0;delete f.We;break;case 2:delete f.bold;f.We=!0;break;case 3:f.bold=!0;f.We=!0;break;default:delete f.bold,delete f.We}e=b.textOpacityOverride?a.A:a.o;f=b.textOpacity;null==f&&(f=d.textOpacity);e.xb.textOpacity=f;e=b.windowOpacityOverride?a.A:a.o;f=b.windowOpacity;null==f&&(f=F4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.A:a.o;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.xb.charEdgeStyle=f;e=b.fontFamilyOverride?a.A:a.o;f=b.fontFamily;null==f&&(f=d.fontFamily);e.xb.fontFamily=f;a.loaded&&a.wt();c&&D4(a,"display-settings",b)},H4=function(a,b){if(b&&!a.F){var c=w3({He:0,
lang:"en"});a.F=[c,new t3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.YK(a.player,a.F)}else!b&&a.F&&(G4(a,a.F),a.F=null)},G4=function(a,b){g.$K(a.player,b);
(0,g.y)(b,function(c){g.cb(this.G,c)},a);
a.Y.Nj()},v4=function(a,b){if(!a.ba)return null;
try{var c=a.ba.get(b)}catch(d){a.ba.remove(b)}return c},D4=function(a,b,c){if(a.ba)try{a.ba.set(b,c)}catch(d){}};
g.QC.prototype.qj=g.ca(13,function(){for(var a=g.Dd(document,"track",void 0,this.g),b=0;b<a.length;b++)g.Wd(a[b])});
g.BX.prototype.qj=g.ca(12,function(){this.g.qj()});
g.QC.prototype.bl=g.ca(11,function(){return!!this.g.textTracks});
g.BX.prototype.bl=g.ca(10,function(){return this.g.bl()});
g.QC.prototype.ij=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.BX.prototype.ij=g.ca(8,function(a){this.g.ij(a)});
g.HC.prototype.Hh=g.ca(7,function(){});
g.QC.prototype.Hh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.BX.prototype.Hh=g.ca(5,function(){return this.g.Hh()});
g.Zz.prototype.vr=g.ca(3,function(a){return a?this.toString()==a.toString():!1});
g.Wt.prototype.Cm=g.ca(2,function(a){return(a=this.og(a))?a.i:0});
g.Sw.prototype.Cm=g.ca(1,function(){return 0});
var aqa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Kpa=/#(.)(.)(.)/,Jpa=/^#(?:[0-9a-f]{3}){1,2}$/i,b4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.t(k3,g.A);k3.prototype.Qz=function(){return!1};
k3.prototype.V=function(){this.Kg();g.A.prototype.V.call(this)};
g.t(l3,k3);l3.prototype.kr=function(a,b,c){b=this.Kj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Kg();this.g=g.er(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
l3.prototype.lr=function(a){if(this.l)for(var b=g.q(this.l.captionTracks),c=b.next();!c.done;c=b.next())j3(this.i,c.value);a()};
l3.prototype.Kj=function(a,b){var c=a.G,d={fmt:b};a.g&&(d.tlang=g3(a));return g.Oq(c,d)};
l3.prototype.Kg=function(){this.g&&this.g.abort()};
m3.prototype.contains=function(a){a=g.ob(this.Xa,a);return 0<=a||0>a&&1==(-a-1)%2};
m3.prototype.length=function(){return this.Xa.length/2};
g.t(n3,g.A);g.h=n3.prototype;g.h.V=function(){g.A.prototype.V.call(this);this.i&&this.i.cancel()};
g.h.Vx=function(){var a=this.o.getCurrentTime();a-=this.o.Kb();var b=this.g;this.g=g.Va(this.T.Af(a).g);b!=this.g&&this.J&&this.J()};
g.h.reset=function(){this.A=new m3;this.i&&(this.i.cancel(),this.i=null)};
g.h.vx=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Kf(a);!a||this.i||this.g&&30<this.g.startTime-this.o.getCurrentTime()||(a=this.g,a=a.g.wi(a),a.g[0].duration&&(this.A.contains(a.g[0].i)||o3(this,a),this.g=g.Va(a.g)));this.F.start()};
g.h.dL=function(a){var b=!(this.B?a.response:a.responseText)||400<=a.status,c=g.Zw(a);c?(a=g.gw(this.l,this.I,{}),b=this.l,g.bw(b.i,a,c),b.requestId=a.get("req_id"),o3(this,this.l)):(b||null===this.C||(c=this.l.g[0],this.B?this.C(a.response,1E3*(c.startTime+this.o.Kb())):this.C(a.responseText,1E3*(c.startTime+this.o.Kb()))),this.i=this.l=null)};
g.t(p3,k3);g.h=p3.prototype;g.h.kr=function(a,b,c){this.Kg();b=Mpa(this,a.getId());b||(b=a.i,b=this.g.i?r3(this,b,"386"):r3(this,b));if(b){var d=1E3*(b.index.Cm(b.index.ye())-b.index.Mc(b.index.ye()));this.l=new n3(new g.xv,this.C,b,function(e,f){c(e,a,f,d)},this.B||g.qv(b.info),(0,g.x)(function(){this.l&&this.l.reset();
this.o=!0},this))}};
g.h.Qz=function(){var a=this.o;this.o=!1;return a};
g.h.lr=function(a){var b;this.B?b=[new g.Zz({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Zz({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.g.i?q3(this,"386"):q3(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())j3(this.i,c.value);a()};
g.h.Kg=function(){this.l&&(this.l.dispose(),this.l=null)};
g.h.Kj=function(){return""};
g.t(s3,k3);s3.prototype.kr=function(a,b,c){b=this.Kj(a,b);var d=(0,g.x)(function(e){this.g=null;c(e.responseText,a)},this);
this.Kg();this.g=g.er(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
s3.prototype.lr=function(a){var b=this.o,c={type:"list",tlangs:1,v:this.l,vssids:1};this.B&&(c.asrs=1);b=g.Oq(b,c);c=(0,g.x)(function(d){this.g=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.q(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),p=k.getAttribute("id"),r="true"==k.getAttribute("lang_default"),w="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
j3(this.i,new g.Zz({languageCode:f,languageName:l,name:m,kind:n,id:p,is_servable:!0,is_translateable:w,vss_id:k,is_default:r}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),p=d[f].getAttribute("id"),r="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:p,isDefault:r},this.C[l.languageCode]=l.languageName,this.A.push(l)}a()},this);
this.Kg();this.g=g.er(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
s3.prototype.Kj=function(a,b){var c=this.o,d={v:this.l,type:"track",lang:a.i,name:a.getName(),kind:a.o,fmt:b};a.g&&(d.tlang=g3(a));return c=g.Oq(c,d)};
s3.prototype.Kg=function(){this.g&&this.g.abort()};var Npa=["left","right","center","justify"];var F4={windowColor:"#080808",windowOpacity:0,textAlign:2,Yf:7,Xe:50,Jg:100,xb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.t(t3,g.xE);t3.prototype.toString=function(){return g.xE.prototype.toString.call(this)};g.t(u3,g.xE);u3.prototype.toString=function(){return g.xE.prototype.toString.call(this)};
var v3=0;g.t(y3,g.V);g.h=y3.prototype;g.h.tG=function(a,b){var c=g.Oh(this.element,this.element.parentElement);this.oa=a-c.x;this.xa=b-c.y;g.H(this.element,"ytp-dragging")};
g.h.sG=function(a,b){var c=g.Rh(this.element),d=a-this.oa-.02*this.Sa,e=b-this.xa-.02*this.Ra,f=(d+c.width/2)/this.aa*3;f=Math.floor(g.nd(f,0,2));var k=(e+c.height/2)/this.ya*3;k=Math.floor(g.nd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.aa;d=100*g.nd(d,0,1);c=(e+k/2*c.height)/this.ya;c=100*g.nd(c,0,1);this.o.params.Yf=l;this.o.params.Jg=c;this.o.params.Xe=d;this.l.Yf=l;this.l.Jg=c;this.l.Xe=d;this.oA()};
g.h.rG=function(){g.ro(this.element,"ytp-dragging")};
g.h.oA=function(){this.Dh(this.C)};
g.h.Dh=function(a){var b=Math.min(this.hw(),this.aa),c=this.gw(),d="";3==this.o.params.He&&(d="rotate(180deg)");g.yh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.mp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Xe+2;d=this.l.Yf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.Jg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.yh(this.element,a)};
g.h.mp=function(a){var b;for(b=0;b<a.length&&a[b]==this.C[b];b++);if(this.R||this.C.length>b)b=0,this.R=!1,this.C=[],this.F=this.Z=this.U=null,g.Ud(this.B);for(;b<a.length;b++)C3(this,a[b])};
g.h.hw=function(){return 0};
g.h.gw=function(){return 0};
g.h.toString=function(){return g.V.prototype.toString.call(this)};D3.prototype.A=function(){};F3.prototype.clear=function(){this.o=this.i=this.mode=0;this.g=[];this.reset()};
F3.prototype.reset=function(){this.mode=0;this.A.reset(0);this.B.reset(1)};
var G3=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];I3.prototype.set=function(a){this.g=a};
I3.prototype.get=function(){return this.g};
J3.prototype.clear=function(){this.g=0};
J3.prototype.update=function(){this.g=2==this.g?1:0};
J3.prototype.matches=function(a,b){return 0!=this.g&&a==this.l&&b==this.i};
K3.prototype.jg=function(a){this.Yd=a.Yd;this.timestamp=a.timestamp};
K3.prototype.reset=function(){this.timestamp=this.Yd=0};
L3.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.l[b][c].timestamp=a};
L3.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.l[b][c];a=0==d.Yd?a+"_":a+String.fromCharCode(d.Yd)}a+="\n"}return a};
L3.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.l[b][c].reset();this.o=a;this.g=0;this.i=this.row=1};
var Rpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Spa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Tpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Upa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];S3.prototype.reset=function(a,b){this.A=b;this.style.set(2);this.i=this.B;this.l=this.C;this.g=this.i;var c=(a<<2)+(b<<1);this.B.reset(c);this.C.reset(c);this.F.reset((a<<2)+(b<<1)+1)};
E3.prototype.reset=function(a){this.A=a;this.g.clear();this.o=this.l;this.l.reset(a,0);this.B.reset(a,1)};g.t(X3,g.A);X3.prototype.reset=function(){};g.t(Y3,X3);Y3.prototype.reset=function(){this.F={};this.i=this.g=null;this.C=!0};
Y3.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.l,l={},m=c.getAttribute("p");m&&g.Ra(l,this.l[m]);m=$3(c,"b");null!=m&&(l.bold=
m);m=$3(c,"i");null!=m&&(l.We=m);m=$3(c,"u");null!=m&&(l.underline=m);m=a4(c,"et");null!=m&&(l.charEdgeStyle=m);m=a4(c,"of");null!=m&&(l.offset=m);m=c4(c,"bc");null!=m&&(l.background=m);m=c4(c,"ec");null!=m&&(l.av=m);m=c4(c,"fc");null!=m&&(l.color=m);m=a4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=Z3(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=Z3(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=Z3(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=a4(c,"rb");null!=m&&10!=m&&(l.hd=10<m?m-1:m);m=a4(c,
"hg");null!=m&&(l.tE=m);c=a4(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.Ge=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.I[d]=d4(this,c);break;case "wp":d=c.getAttribute("id"),this.G[d]=e4(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=f4(this,d,e,!1);g.B(this,this.g);(d=this.F[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.F[this.g.id]=this.g;c.push(this.g);break;case "p":var n=
e;k=[];l=d.getAttribute("w")||this.A;m=!!$3(d,"a");n=(Z3(d,"t")||0)+n;var p=Z3(d,"d")||5E3;m||(!this.C&&this.i&&this.i.windowId==l&&this.i.end>n&&(this.i.end=n),this.i&&"\n"==this.i.text&&(this.i.text=""));var r=m?6:5,w=this.l[d.getAttribute("p")],z=[].concat(g.ea(d.childNodes));z.length&&(this.C=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var F=z[C],E=void 0;0<C&&(m=!0);var K=void 0;1==F.nodeType&&(K=F);if(K&&"s"==K.tagName){if((F=this.l[K.getAttribute("p")])&&F.hd&&(1==F.hd?(F=z.slice(C,
C+4),4==F.length&&(E=W3(n,p,l,m,r,F,this.l),C+=3)):E=W3(n,p,l,m,r,[K],this.l)),!E){var Q=K;E=n;K=p;F=l;var W=m,ta=r,db=Q.textContent?Q.textContent:"",we=this.l[Q.getAttribute("p")];Q=Z3(Q,"t")||0;E=new t3(E+Q,K-Q,ta,F,db,W,we)}}else E=new t3(n,p,r,l,F.textContent||"",m,w);k.push(E);this.i=E}if(0<k.length)for(k[0].windowId==this.A&&(this.g=f4(this,d,e,!0),g.B(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.B(l,k),l.g.push(k),c.push(k)}e=
c}else e=[];return e};g.t(g4,y3);g4.prototype.mp=function(a){var b=this.o.g;y3.prototype.mp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.g==e)var d=f;else{d={};g.Ra(d,c.g);g.Ra(d,bqa);var e=c.g;var f=d}C3(this,c,d)}};
var bqa={rE:!0};g.t(h4,D3);h4.prototype.A=function(a,b,c,d,e){if(c<d){var f="_"+v3++;c=c/1E3-this.C;d=d/1E3-this.C;a=new u3(c,d-c,5,f,{textAlign:0,Yf:0,Xe:2.5*b,Jg:5.33*a});e=new t3(c,d-c,5,f,e);this.l.push(a);this.l.push(e)}};
g.t(k4,X3);k4.prototype.o=function(a){a=new h4(a,a.byteLength,this.i);if(l4(a)){for(;a.g<a.i.byteLength;)for(0==a.version?a.o=j4(a)*(1E3/45):1==a.version&&(a.o=4294967296*j4(a)+j4(a)),a.B=i4(a);0<a.B;a.B--){var b=i4(a),c=i4(a),d=i4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.o,type:this.track,Uu:c,Vu:d,order:b.g.length}))}Qpa(this.g,a);return a.l}return[]};
k4.prototype.reset=function(){this.g.clear()};g.t(n4,y3);g.h=n4.prototype;g.h.oA=function(){g.Fo(this.fa)};
g.h.iL=function(){g.ro(this.element,"ytp-rollup-mode");this.Dh(this.Fa,!0)};
g.h.gw=function(){return this.A?this.J:this.I};
g.h.hw=function(){return this.A?this.I:this.J};
g.h.Dh=function(a,b){this.Fa=a;if(this.o.params.Mk){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.za=this.J;this.I=this.J=0;y3.prototype.Dh.call(this,a);Zpa(this,b);y3.prototype.Dh.call(this,a)}else y3.prototype.Dh.call(this,a)};g.t(p4,X3);
p4.prototype.o=function(a,b){for(var c=[],d=a.split(cqa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!dqa.test(f)){var l=I4.exec(f);if(l&&4<=l.length){var m=r4(l[1]),n=r4(l[2])-m;m+=k;var p,r=p=void 0,w=void 0,z=void 0,C=l[3];l={textAlign:2};C=g.q(C?C.split(" "):[]);for(var F=C.next();!F.done;F=C.next())if(F=F.value.split(":"),2==F.length){var E=F[1];switch(F[0]){case "line":F=E.split(",");F[0].endsWith("%")&&(z=F[0],l.Jg=Number.parseInt(z,10),2==F.length&&(w=F[1].trim()));break;case "position":F=E.split(",");
r=F[0];l.Xe=Number.parseInt(r,10);2==F.length&&(p=F[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Jg=100,w||(w="end"));if(!r)switch(l.textAlign){case 0:l.Xe=0;break;case 1:l.Xe=100;break;default:l.Xe=50}r=0;switch(w){case "center":r+=3;break;case "end":r+=6;break;default:r+=0}switch(p){case "line-left":r+=0;break;case "center":r+=1;break;case "line-right":r+=2;break;default:switch(l.textAlign){case 0:r+=
0;break;case 2:r+=1;break;case 1:r+=2}}l.Yf=0>r||8<r?7:r;p=l;f=f.substring(I4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=s4(m,n,5,r),n=new t3(m,n,5,k.id,p,!1,g.Xb(f)?void 0:f),c.push(k),c.push(n),g.B(k,n),k.g.push(n);else for(w=p.split(eqa),1==w.length?(p=5,r=s4(m,n,p,r)):(z=p=6,r=Object.assign({Zl:32},r),r=new u3(m,n,z,"_"+v3++,r)),c.push(r),z=m,l=0;l<w.length;l++)C=w[l],0==l%2?(F=g.to("<html>"+C+"</html>"),F.getElementsByTagName("parsererror").length?
(E=F.createElement("span"),E.appendChild(F.createTextNode(C))):E=F.firstChild,q4(this,z,n-(z-m),p,r,0<l,E,f,c)):z=r4(C)+k}I4.lastIndex=0}}return c};
var dqa=/^NOTE/,cqa=/(?:\r\n|\r|\n){2,}/,I4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),eqa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.t(t4,g.A);t4.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
t4.prototype.reset=function(){this.g&&this.g.reset()};
t4.prototype.V=function(){this.clear();g.A.prototype.V.call(this)};g.t(w4,g.uL);g.h=w4.prototype;g.h.V=function(){if(this.B||this.I){var a=this.N.app.A;a&&a.qj()}else H4(this,!1);g.uL.prototype.V.call(this)};
g.h.Sk=function(){return this.ra?this.B||this.I:y4(this)?!0:x4(this)};
g.h.load=function(){g.uL.prototype.load.call(this);var a=!g.O(this.l.experiments,"web_player_captions_track_list_changed_killswitch");this.C=this.player.getAudioTrack();if(this.i)this.g&&(this.Z.clear(),this.B?C4(this,!0):3!=this.player.getPresentingPlayerType()&&this.i.kr(this.g,"srv3",(0,g.x)(this.QL,this)),!a||this.B||this.I||B4(this)||this.player.na("captionschanged",f3(this.g))),a||(this.g&&!B4(this)?this.player.na("captionschanged",f3(this.g)):this.player.na("onCaptionsTrackListChanged"));else{var b;
this.fa?b=new p3(this.P.ka,this.player):this.xa?b=new l3(this.l,this.P,this.player.getAudioTrack()):b=new s3(this.P.oj,this.P.videoId,this.P.dg||this.l.dg||g.gC(this.P,"yt:cc_default_lang")||this.l.Yb,this.P.xp,this.l);this.i=b;g.B(this,this.i);b.lr((0,g.x)(this.PL,this))}};
g.h.unload=function(){this.B&&this.g?C4(this,!1):(this.aa&&g.Go(this.aa),g.aL(this.player,"captions"),this.G=[],this.i&&this.i.Kg(),this.Z.clear(),this.F&&g.YK(this.player,this.F),this.wt());g.uL.prototype.unload.call(this);var a=g.U(this.player.app);a&&g.EI(a.A);this.player.na("captionschanged",{})};
g.h.PL=function(){var a;this.J||x4(this)?a=A4(this,this.J):y4(this)&&(a=z4(this));if(this.B||this.I){for(var b=i3(this.i.i,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.$z(e),srclang:g3(e),id:e.toString()};this.I||(f.src=this.i.Kj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Qd("TRACK",f))}a=this.N.app.A;a.ij(c);c=a.ia();this.ma&&this.da.L(c.textTracks,"change",this.RL)}else!this.g&&a&&E4(this,a),this.player.na("onCaptionsTrackListChanged"),this.player.na("onApiChange")};
g.h.RL=function(){for(var a=this.N.app.A.ia().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=i3(this.i.i,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.g:null)!=b&&E4(this,b,!0)};
g.h.wN=function(){!this.g&&this.B||this.unload()};
g.h.QL=function(a,b,c,d){if(a){this.i.Qz()&&(this.G=[],g.aL(this.N,"captions"),this.Y.Nj(),this.Z.reset());var e=this.Z;c=c||0;d=d||0;if(!g.Da(a)){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.ou(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!m4(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=
a[k++];var p=a[k++],r=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|r&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}}if(a)try{if(g.Da(a)){if("WEBVTT"==a.substring(0,6)){b=a;var w=c;e.g||(e.g=new p4);var z=e.g.o(b,w);.01>Math.random()&&g.cq(Error("Deprecated subtitles format in web player: WebVTT"));var C=z}else b:{z=a;w=g.to(z);if(!w||!w.firstChild){var F=Error("Invalid caption track data");
F.params=z;throw F;}if("timedtext"==w.firstChild.tagName){if(3==parseInt(w.firstChild.getAttribute("format"),10)){if(!e.g){z={};var E=g3(b);E&&(z.lang=E,aqa.test(E)&&(z.He=1));e.g=new Y3(z,e.i)}C=e.g.o(w,c);break b}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=z;throw K;}if("transcript"==w.firstChild.tagName){var Q=Error("Unsupported subtitles format in web player (Format1)");Q.params=z;throw Q;}var W=Error("Invalid caption track data");W.params=z;throw W;}var ta=C}else{C=
a;w=c;E=d;if(!m4(C))throw Error("Invalid binary caption track data");e.g||(e.g=new k4(E,b));ta=e.g.o(C,w)}var db=ta}catch(we){g.L(we),e.clear(),db=[]}else db=[];g.YK(this.player,db);!this.J||this.I||B4(this)||g.tz(this.l)||g.vz(this.l)||(g.Go(this.aa),db=w3({Yf:0,Xe:5,Jg:5,Mk:2,textAlign:0,He:0,lang:"en"}),this.R=[db],e=["Click "," for settings"],this.ha||(ta=new g.sD(g.zQ()),g.B(this,ta),this.ha=ta.element),ta=db.end-db.start,(b=g.$z(this.g))&&this.R.push(new t3(db.start,ta,0,db.id,b)),this.R.push(new t3(db.start,
ta,0,db.id,e[0]),new t3(db.start,ta,0,db.id,this.ha,!0),new t3(db.start,ta,0,db.id,e[1],!0)),g.YK(this.player,this.R),g.Eo(this.aa));!this.J||this.I||B4(this)||(D4(this,"module-enabled",!0),this.C&&(this.C.g=this.g),(db=g.U(this.player.app))&&g.EI(db.A));this.J=!1}};
g.h.zF=function(a){this.G.push(a);this.Y.Nj()};
g.h.AF=function(a){g.cb(this.G,a);this.i instanceof p3&&this.i.B&&g.$K(this.player,[a]);this.Y.Nj()};
g.h.GM=function(a){if(a instanceof u3){var b=this.T[a.id];b&&b.o!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=$pa(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.U[b]||(this.U[b]=[]),this.U[b].push(a)};
g.h.MM=function(){G4(this,this.R);this.R=null};
g.h.lB=function(){this.Y.stop();g.Yb(this.U);this.G.sort(g.zE);var a=this.G;if(this.F){var b=(0,g.Xd)(a,function(c){return-1==this.F.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.GM,this);g.Kb(this.T,function(c,d){this.U[d]?(c.element.parentNode||g.eL(this.player,c.element,4),c.Dh(this.U[d])):(c.dispose(),delete this.T[d])},this)};
g.h.SM=function(){u4(this,{},!0);g.O(this.l.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.na("captionssettingschanged")};
g.h.GD=function(){var a=F4.xb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.We?3:a.bold?1:a.We?2:0,textOpacity:a.textOpacity,windowColor:F4.windowColor,windowOpacity:F4.windowOpacity};var b=v4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.rB=function(a,b){var c={};g.Ra(c,v4(this,"display-settings"));g.Ra(c,a);u4(this,c,b);this.player.na("captionssettingschanged")};
g.h.wt=function(){!this.B&&this.loaded&&(g.Kb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.lB())};
g.h.yc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.nd(b,-2,4);this.rB({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&E4(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.zb&&D4(this,"module-enabled",!!b);break;case "track":if(!this.i)return{};if(b){if(this.B)break;if(!g.Na(b))break;if(g.Xb(b)){E4(this,null,!0);break}for(var d=i3(this.i.i,!0),e=0;e<d.length;e++){var f=d[e];f.i!=b.languageCode||c&&f.l!=b.languageName||(c=b.translationLanguage?Ipa(f,b.translationLanguage):
f)}!c||c==this.g&&this.loaded||E4(this,c,!0)}else return this.loaded&&this.g&&!B4(this)?f3(this.g):{};return"";case "tracklist":return this.i?(0,g.ge)(i3(this.i.i,!(!b||!b.includeAsr)),function(k){return f3(k)}):[];
case "translationLanguages":return this.i?this.i.A.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||H4(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.l.zb&&a.push("stickyLoading");return a};
g.h.Mj=function(){var a=this.g;return a?{cc:a.B}:{}};
g.h.qN=function(){this.loaded&&this.g&&!B4(this)?(D4(this,"module-enabled",!1),this.unload(),y4(this,!0)&&E4(this,z4(this),!1)):E4(this,B4(this)||!this.g?A4(this,!0):this.g,!0)};
g.h.JI=function(){var a=B4(this);y4(this,a)?E4(this,this.player.getAudioTrack().om,!1):this.P.captionTracks.length&&(this.loaded&&this.unload(),this.Sk()&&(a?E4(this,A4(this),!1):this.load()))};g.QV.captions=w4;})(_yt_player);
