(function(g){var window=this;var K4=function(a,b,c){var d=b.wa();g.I(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Bc(c?c:"mqdefault.jpg");var f=b instanceof g.CB&&b.lengthSeconds?g.wR(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.BE(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.CB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.jj||g.bO("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.bi(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.DE&&(d.playlist_length=b.getLength());a.update(d)},L4=function(a,b){g.yD.call(this,{D:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},M4=function(a){g.V.call(this,{D:"div",
X:["ytp-upnext","ytp-player-content"],M:{"aria-label":"{{aria_label}}"},K:[{D:"div",H:"ytp-cued-thumbnail-overlay-image",M:{style:"{{background}}"}},{D:"span",H:"ytp-upnext-top",K:[{D:"span",H:"ytp-upnext-header",W:"Up Next"},{D:"span",H:"ytp-upnext-title",W:"{{title}}"},{D:"span",H:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",H:"ytp-upnext-autoplay-icon",M:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",M:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
H:"ytp-svg-autoplay-circle",M:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",H:"ytp-svg-autoplay-ring",M:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",H:"ytp-svg-fill",M:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",H:"ytp-upnext-bottom",K:[{D:"span",H:"ytp-upnext-cancel"},{D:"span",H:"ytp-upnext-paused",W:"Autoplay is paused"}]}]});
this.B=null;var b=this.i["ytp-upnext-cancel"];this.B=new g.V({D:"button",X:["ytp-upnext-cancel-button","ytp-button"],M:{tabindex:"0","aria-label":"Cancel autoplay"},W:"Cancel"});g.B(this,this.B);this.B.ea("click",this.OI,this);this.B.g(b);this.l=a;this.J=this.i["ytp-svg-autoplay-ring"];this.F=this.C=this.o=this.A=null;this.G=new g.J(this.Yl,5E3,this);g.B(this,this.G);this.I=0;this.L(this.i["ytp-upnext-autoplay-icon"],"click",this.CK);this.Uy();this.L(a,"autonavvisibility",this.Uy);this.L(a,"mdxnowautoplaying",
this.VJ);this.L(a,"mdxautoplaycanceled",this.WJ);this.L(a,"mdxautoplayupnext",this.qB);3==this.l.getPresentingPlayerType()&&(a=(a=g.SK(g.MK(this.l)))?a.ED():null)&&this.qB(a)},N4=function(a,b){if(!a.o){g.rq("a11y-announce","Up Next "+a.A.title);
a.I=g.M();a.o=new g.J((0,g.x)(a.lp,a,b),25);a.lp(b);var c=b||g.P(g.X(a.l).experiments,"autoplay_time")||1E4;a.l.na("onAutonavCoundownStarted",c)}g.ro(a.element,"ytp-upnext-autoplay-paused")},P4=function(a){O4(a);
a.I=g.M();a.lp();g.H(a.element,"ytp-upnext-autoplay-paused")},O4=function(a){a.o&&(a.o.dispose(),a.o=null)},Q4=function(a,b){b=void 0===b?!1:b;
if(g.O(g.X(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.wa(),a.Yl(),a.C=new Notification("Up Next",{body:c.title,icon:c.Bc()}),a.F=a.L(a.C,"click",a.uK),a.G.start())}O4(a);a.l.nextVideo(!1,b)},R4=function(a){L4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.V({D:"div",H:"ytp-subscribe-card",K:[{D:"img",H:"ytp-author-image",M:{src:b.Wd}},{D:"div",H:"ytp-subscribe-card-right",K:[{D:"div",H:"ytp-author-name",W:b.author},{D:"div",H:"html5-subscribe-button-container"}]}]});g.B(this,this.l);this.l.g(this.element);this.o=new g.JW("Subscribe",null,"Unsubscribe",null,!0,!1,b.Uf,b.subscribed,"trailer-endscreen",null,null,a);g.B(this,this.o);this.o.g(this.l.i["html5-subscribe-button-container"]);this.hide()},S4=function(a){var b=
g.X(a),c=g.tx||g.Bh?{style:"will-change: opacity"}:void 0,d=b.i,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",X:e,M:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",H:"ytp-videowall-still-image",M:{style:"{{background}}"}},{D:"span",H:"ytp-videowall-still-info",K:[{D:"span",H:"ytp-videowall-still-info-bg",K:[{D:"span",H:"ytp-videowall-still-info-content",M:c,K:[{D:"span",H:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",H:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",H:"ytp-videowall-still-info-live",W:"Live"},{D:"span",H:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",H:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",H:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",H:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",H:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.Xs(this);g.B(this,this.A);this.ea("click",this.F);this.ea("keypress",this.G);this.A.L(a,"videodatachange",this.C);g.X(a).F&&g.QO(a.app.U,this.element,this);this.C()},T4=function(a){g.hL(a.l,a.element);
var b=a.o.wa().videoId,c=a.o.getPlaylistId();g.QY(a.l.app,b,a.o.Db,c,void 0,void 0)},U4=function(a){L4.call(this,a,"videowall-endscreen");
this.C=a;this.B=0;this.o=[];this.F=this.P=this.A=null;this.G=this.R=!1;this.N=null;this.da=new g.Xs(this);g.B(this,this.da);this.I=new g.J(g.Qa(g.H,this.element,"ytp-show-tiles"),0);g.B(this,this.I);var b=new g.V({D:"button",X:["ytp-button","ytp-endscreen-previous"],M:{"aria-label":"Previous"},K:[g.eQ()]});g.B(this,b);b.g(this.element);b.ea("click",this.fG,this);this.J=new g.sD({D:"div",H:"ytp-endscreen-content"});g.B(this,this.J);this.J.g(this.element);b=new g.V({D:"button",X:["ytp-button","ytp-endscreen-next"],
M:{"aria-label":"Next"},K:[g.fQ()]});g.B(this,b);b.g(this.element);b.ea("click",this.eG,this);this.l=new M4(a);g.B(this,this.l);g.eL(this.player,this.l.element,4);this.hide()},V4=function(a){return g.fL(a.player)&&a.Ku()&&!a.F},W4=function(a,b){return(0,g.ge)(b.suggestions,function(c){c=g.LS(g.X(a.C),c);
g.B(a,c);return c})},X4=function(a){var b=a.Te();
b!=a.R&&(a.R=b,a.player.O("autonavvisibility"))},Z4=function(a){g.uL.call(this,a);
this.g=null;this.i=new g.Xs(this);g.B(this,this.i);this.l=g.X(a);Y4(a)?this.g=new U4(this.player):this.l.Ka?this.g=new R4(this.player):this.g=new L4(this.player);g.B(this,this.g);g.eL(this.player,this.g.element,4);this.nA();this.i.L(a,"videodatachange",this.nA,this);this.i.L(a,g.AE("endscreen"),this.tF,this);this.i.L(a,"crx_endscreen",this.uF,this)},Y4=function(a){a=g.X(a);
return a.Fa&&!a.Ka};
g.t(L4,g.yD);L4.prototype.create=function(){this.created=!0};
L4.prototype.destroy=function(){this.created=!1};
L4.prototype.Ku=function(){return!1};
L4.prototype.Te=function(){return!1};g.t(M4,g.V);g.h=M4.prototype;g.h.Yl=function(){this.C&&(this.G.stop(),this.Oa(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.Uy=function(){g.xD(this,this.l.Te())};
g.h.uK=function(){window.focus();this.Yl()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.lp=function(a){a=a||g.P(g.X(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.M()-this.I,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.getPresentingPlayerType()?Q4(this,!0):this.o&&this.o.start()};
g.h.CK=function(a){!g.$d(this.B.element,g.ps(a))&&g.OS(a,this.l)&&Q4(this)};
g.h.OI=function(){g.OK(this.l,!0)};
g.h.VJ=function(a){this.l.getPresentingPlayerType();this.show();N4(this,a)};
g.h.qB=function(a){this.l.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,K4(this,a,"hqdefault.jpg"))};
g.h.WJ=function(){this.l.getPresentingPlayerType();O4(this);this.hide()};
g.h.V=function(){O4(this);this.Yl();g.V.prototype.V.call(this)};g.t(R4,L4);g.t(S4,g.V);S4.prototype.F=function(a){g.OS(a,this.l,this.B,this.o.Db||void 0)&&T4(this)};
S4.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.vs(a)||(T4(this),g.us(a))}};
S4.prototype.C=function(){var a=this.l.getVideoData(),b=g.X(this.l);this.B=a.Dc?!1:b.i};g.t(U4,L4);g.h=U4.prototype;g.h.create=function(){L4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.A=W4(this,a),this.P=a);this.Mf();this.da.L(this.player,"appresize",this.Mf);this.da.L(this.player,"onVideoAreaChange",this.Mf);this.da.L(this.player,"videodatachange",this.gG);this.da.L(this.player,"autonavchange",this.zr);this.da.L(this.player,"autonavcancel",this.dG);a=this.P.autonavState;a!=this.N&&this.zr(a);this.da.L(this.element,"transitionend",this.SL)};
g.h.destroy=function(){g.Zs(this.da);g.qf(this.o);this.o=[];this.A=null;L4.prototype.destroy.call(this);g.ro(this.element,"ytp-show-tiles");this.I.stop();this.N=this.P.autonavState};
g.h.Ku=function(){return 1!=this.P.autonavState};
g.h.show=function(){L4.prototype.show.call(this);g.ro(this.element,"ytp-show-tiles");g.X(this.player).g?g.Fo(this.I):this.I.start();(this.G||this.F&&this.F!=this.P.clientPlaybackNonce)&&g.OK(this.player,!1);V4(this)?(X4(this),2==this.P.autonavState?g.O(g.X(this.player).experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?Q4(this.l,!0):N4(this.l):3==this.P.autonavState&&P4(this.l)):(g.OK(this.player,!0),X4(this))};
g.h.hide=function(){L4.prototype.hide.call(this);P4(this.l);X4(this)};
g.h.SL=function(a){g.ps(a)==this.element&&this.Mf()};
g.h.Mf=function(){if(this.A&&this.A.length){g.H(this.element,"ytp-endscreen-paginate");var a=g.WK(this.C,!0,this.C.isFullscreen()),b=g.OD(this.C);b&&(b=b.ec()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.A.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,r=e/2,w=b<=f-2&&n>=r*m,z=e<=k-2&&n>=p*m;if((p+1)/r*d/c>c/(p/(r+1)*d)&&z)n-=p*m,e+=2;else if(w)n-=r*m,b+=2;else if(z)n-=
p*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.nd(a.width/m||1,1,1.21);n*=g.nd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.J.element;g.Qh(a,m,n);g.yh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.A[0];c.A=f;K4(c,f,"hqdefault.jpg");g.I(this.element,"ytp-endscreen-takeover",V4(this));X4(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=
c,r=0,d&&f>=b-2&&k>=e-2?r=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(r=2):r=2),p=g.od(p+this.B,l),0!=r){w=this.o[c];w||(w=new S4(this.player),this.o[c]=w,a.appendChild(w.element));z=Math.floor(n*k/e);var C=Math.floor(m*f/b),F=Math.floor(n*(k+r)/e)-z-4,E=Math.floor(m*(f+r)/b)-C-4;g.Gh(w.element,C,z);g.Qh(w.element,E,F);g.yh(w.element,"transitionDelay",(k+f)/20+"s");g.I(w.element,"ytp-videowall-still-mini",1==r);g.I(w.element,"ytp-videowall-still-large",2<r);r=w;p=this.A[p];r.o!=p&&(r.o=p,K4(r,p,g.po(r.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.Db)&&p.itct)&&(w=r.l,g.X(w).F&&g.RO(w.app.U,r.element,p));c++}g.I(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Wd(e.element),g.pf(e);this.o.length=c}};
g.h.gG=function(){var a=this.player.getVideoData();this.P!=a&&(this.B=0,this.A=W4(this,a),this.P=a,this.Mf())};
g.h.eG=function(){this.B+=this.o.length;this.Mf()};
g.h.fG=function(){this.B-=this.o.length;this.Mf()};
g.h.IE=function(){return!!this.l.o};
g.h.zr=function(a){1==a?(this.G=!1,this.F=this.P.clientPlaybackNonce,O4(this.l),this.Ga()&&this.Mf()):(this.G=!0,this.Ga()&&V4(this)&&(2==a?N4(this.l):3==a&&P4(this.l)))};
g.h.dG=function(a){if(a){for(a=0;a<this.o.length;a++)g.iL(this.C,this.o[a].element,!0);this.zr(1)}else this.F=null,this.G=!1;this.Mf()};
g.h.Te=function(){return this.Ga()&&V4(this)};g.t(Z4,g.uL);g.h=Z4.prototype;g.h.Sk=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Y4(this.player)||b;a=a.Rc||g.lz(a.Pa);var c=g.pY(this.player.app);return b&&!a&&!c};
g.h.Te=function(){return this.g.Te()};
g.h.DE=function(){return this.Te()?this.g.IE():!1};
g.h.V=function(){g.aL(this.player,"endscreen");g.uL.prototype.V.call(this)};
g.h.load=function(){g.uL.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.uL.prototype.unload.call(this);this.g.hide();this.g.destroy()};
g.h.tF=function(a){this.Sk()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.uF=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.nA=function(){g.aL(this.player,"endscreen");var a=this.player.getVideoData();a=new g.xE(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.B(this,a);var b=new g.xE(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.B(this,b);g.YK(this.player,[a,b])};g.QV.endscreen=Z4;})(_yt_player);
